# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_auto_20190625_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='granted',
        ),
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.ManyToManyField(related_name='granted_wish', to='wish_app.User'),
        ),
    ]
